dat %>% select(age:recovery_time) %>% 
  tbl_summary(type = list(gender ~ "categorical", 
                          race ~ "categorical", 
                          smoking ~ "categorical", 
                          hypertension ~ "categorical",
                          diabetes ~ "categorical", 
                          vaccine ~ "categorical", 
                          severity ~ "categorical",
                          study ~ "categorical",
                          age ~ "continuous",
                          height ~ "continuous",
                          weight ~ "continuous",
                          bmi ~ "continuous",
                          SBP ~ "continuous",
                          LDL ~ "continuous",
                          recovery ~ "continuous"
  ), 
  statistic = list(all_continuous() ~ "{mean} ({sd})"), 
  digits = all_continuous() ~ 1,
  label = list(c(gender) ~ "Gender", 
               c(race) ~ "Race", 
               c(smoking) ~ "Smoking", 
               c(hypertension) ~ "Hypertension",
               c(diabetes) ~ "Diabetes", 
               c(vaccine) ~ "Vaccine", 
               c(severity) ~ "Severity",
               c(study) ~ "Study",
               c(age) ~ "Age",
               c(height) ~ "Height",
               c(weight) ~ "Weight",
               c(bmi) ~ "Body Mass Index",
               c(SBP) ~ "Systolic blood pressure",
               c(LDL) ~ "low-density lipoprotein (cholesterol)",
               c(recovery_time) ~ "Recovery Time") 
  )